### ISSUE TITLE
Connection error Snowflake and Docker Compose/ECS

### ISSUE THREAD

**Issue by TomEijk** [SlalomBuild/snowflake-on-ecs#7]
Hi,

First of all, thank you so much for creating this repo!

When performing all the steps described in the repo, I can't connect to the Airlfow web UI at the end. 
The network container is up and running but the webserver container restarts continuously and provides the following log over and over again: 

`: No such file or directoryn/env: bash`

When checking, for example, the 'docker-compose-local.yml' file, I noticed this is the part where a connection with Snowflake is realized.

`    webserver:
        image: slalombuild/airflow-ecs:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # Set values for your Snowflake account
            - SNOWFLAKE_ACCOUNT=ab12345
            - SNOWFLAKE_REGION=us-west-2
            - SNOWFLAKE_USER=snowflake_user
            - SNOWFLAKE_PASSWORD=xxxxxxxx
        volumes:
            - ./airflow/dags:/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3`

I set the correct values for my snowflake account (assuming that SNOWFLAKE_ACCOUNT needs [account_name].[region] and tried [account_name] as well) but there still seems to be no such file or directoryn/env present. The same holds for my ECS instances by the way. Could you please help me out with this issue? 

Kind regards, 

Tom

**Comment by davemasino** [comment]
Hi, thank you for raising the issue. It looks like there are a few problems related to Python dependencies and access to one of the source datasets. We will be upgrading to Airflow 2.0 in the future.

**Comment by davemasino** [comment]
Closing this issue. Re-creating a new one for Airflow 2.0 upgrade

**Comment by davemasino** [comment]
We are working on resolving the dependency issues with Airflow 1.10.x

**Comment by davemasino** [comment]
@TomEijk we've fixed the issues with the container image. All unit tests are passing. You can also test it out using the "Docker compose" local method described in the README. It should work in AWS now.
